name: ci

on:
  push:
    branches: ['**']  # Trigger on any branch
  pull_request:
    branches: [master]
  # Allows for manually triggering workflow runs.
  workflow_dispatch:

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fetch dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libelf-dev libssl-dev libcap-dev linux-tools-`uname -r`

      - name: Update toolchain
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install g++-12
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 1
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 1

      - name: Build
        run: bazel build //src:all //src/quipper:all

      - name: Test
        run: bazel test //src:all //src/quipper:all

  test-deb-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libelf-dev libssl-dev libcap-dev ruby-dev build-essential

      - name: Install FPM
        run: |
          sudo gem install --no-document fpm

      - name: Test .deb package build
        run: |
          ./scripts/build-deb.sh v0.0.0-test

      - name: Validate .deb package
        run: |
          # Check that the package was created
          ls -la artifacts/
          test -f artifacts/perf-data-converter_0.0.0-test_all.deb

          # Check package contents
          dpkg-deb --contents artifacts/perf-data-converter_0.0.0-test_all.deb

          # Check package info
          dpkg-deb --info artifacts/perf-data-converter_0.0.0-test_all.deb

          # Verify the binary is included and executable
          dpkg-deb --contents artifacts/perf-data-converter_0.0.0-test_all.deb | grep "perf_to_profile"

      - name: Test package installation
        run: |
          # Install the package
          sudo dpkg -i artifacts/perf-data-converter_0.0.0-test_all.deb || true
          sudo apt-get install -f -y  # Fix any dependency issues

          # Test that the binary works
          /usr/local/bin/perf_to_profile --help || echo "Binary help test completed"

          # Test that it's in PATH (if /usr/local/bin is in PATH)
          which perf_to_profile || echo "Binary not in PATH (expected)"

      - name: Upload test .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-deb-package
          path: artifacts/*.deb
          retention-days: 7
